# a simple makefile to run all and clean up

#DATAPATH=/media/1TB_USB3/Tsu-DAT_Data
DATAPATH=/data/indo_ptha

all:
	-python run_all.py "$(DATAPATH)"

clean:
	rm -f *.csv *.txt o_amp_green.cc
	rm -f *.pyc

